receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  batch:
    timeout: 5s
    send_batch_size: 1024
  resourcedetection:
    detectors: [ gcp ]
    timeout: 10s

exporters:
  googlecloud:
    project: alpine-eon-381904
    log:
      default_log_name: opentelemetry.io/collector-exported-log

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
