version: '3.0'

services:
  collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: collector
    hostname: collector
    command: [ "--config=/etc/collector-config.yaml" ]
    environment:
      - AWS_PROFILE=default
    volumes:
      - ./collector-config-gcp.yaml:/etc/collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "5555:5555"

